// Auto-generated by scripts/build-electron.js — do not edit manually
// To regenerate: node scripts/build-electron.js <profile>
// Active profile: mws
export const PROFILE = 'mws';
export const PRODUCT_NAME = 'MWS Desktop';
export const APP_ID = 'com.contactototal.mws-desktop';
export const DEFAULT_BACKEND_URL = process.env.BACKEND_URL || 'https://mws.digitalclub.com.pe';
export const DEFAULT_ANGULAR_URL = process.env.ANGULAR_URL || 'https://mws.digitalclub.com.pe/';
