// Auto-generated by scripts/build-electron.js — do not edit manually
// To regenerate: node scripts/build-electron.js <profile>
// Active profile: infinance
export const PROFILE = 'infinance';
export const PRODUCT_NAME = 'InFinance Desktop';
export const APP_ID = 'com.innovag.infinance-desktop';
export const DEFAULT_BACKEND_URL = process.env.BACKEND_URL || 'https://infinance.innovag.com.pe';
export const DEFAULT_ANGULAR_URL = process.env.ANGULAR_URL || 'https://infinance.innovag.com.pe/';
