// Auto-generated by scripts/build-electron.js — do not edit manually
// To regenerate: node scripts/build-electron.js <https://domain.com>
export const DEFAULT_BACKEND_URL = process.env.BACKEND_URL || 'https://infinance.innovag.com.pe';
export const DEFAULT_ANGULAR_URL = process.env.ANGULAR_URL || 'https://infinance.innovag.com.pe/';
